stages:
  - generate
  - trigger

generate-config:
  stage: generate
  script: bash generate-jobs.sh
  artifacts:
    paths:
      - config.yml

trigger-pipelines:
  stage: trigger
  trigger:
    include:
      - artifact: config.yml
        job: generate-config
    strategy: depend
